# corona-app.yaml

apiVersion: v1
kind: Service
metadata:
  name: corona-map
  labels:
    app: corona-map
spec:
  selector:
    app: corona-map
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP


---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: corona-map
spec:
  schedule: "0 0 * * * "
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: corona-map
        spec:
          restartPolicy: OnFailure
          containers:
          - name: corona-map
            image: parkes9509/corona:{{ .Values.version }}
            ports:
            - name: corona-map-port
              containerPort: 5001
